### ISSUE TITLE
Fallo los controles laterales

### ISSUE THREAD

**Issue by martaquintana** [SoulDreamGames/SoulDreamGame#10]
Al pulsar A o D no permiten moverse a izquierda y derecha. PASOS PARA REPRODUCIRLO Intentar
moverse a izquierda o derecha.

Los controles son un poco confusos en ese aspecto, aunque cuando juegas un rato lo pillas, y también es bastante complicado controlar la dirección de vuelo con el ratón del portátil. Unas instrucciones de dentro del juego comentando los controles y como se puntúa vendrían bien. 

Por cierto, es una pasada de juego!! Y los escenarios son alucinantes!

**Comment by SoulDreamGames** [comment]
¡Hola!
Los controles A y D han sido diseñados de esta manera para que sirvan únicamente como apoyo durante el vuelo, siendo el único desplazamiento real al andar con W o S. Sin embargo, es cierto que faltaba muchha explicación tanto en controles como en desarrollo del juego, por lo que hemos incluido una sección de tutorial.
Además, hemos mejorado el control del vuelo.

Y ¡muchas gracias por el comentario! ¡Mucho ánimo en vuestro desarrollo también!
