### ISSUE TITLE
Elemento sin utilizad aparente en el menú de personalización

### ISSUE THREAD

**Issue by migueljgranizo** [SoulDreamGames/SoulDreamGame#3]
En el menú de personalización del personaje, los botones de la derecha no parecen tener ninguna.

**Comment by martaquintana** [comment]
![image](https://user-images.githubusercontent.com/43533605/232117071-d82d2692-be59-43b6-be98-07b28d59e4e6.png)

**Comment by SoulDreamGames** [comment]
Muchas gracias por el feedback. Esos botones debían cambiar el color del "trail" que deja el jugador al volar, aunque aún no estaba implementado. Ya está solucionado!
