### ISSUE TITLE
Animación de caída espontánea

### ISSUE THREAD

**Issue by migueljgranizo** [SoulDreamGames/SoulDreamGame#4]
Si pasas de un punto a otro, estando el primero ligeramente a más altura, ejecuta una animación de caída.
Sucede al salir, por ejemplo, de una zona de carretera a una de césped.

**Comment by SoulDreamGames** [comment]
Muchas gracias por el feedback. Los colliders de ambos objetos se encontraban a distinta altura y, por ello, a veces el jugador caía sin motivo aparente. Ya lo hemos solucionado!
