### ISSUE TITLE
Fallo la sincronización de animación y movimiento

### ISSUE THREAD

**Issue by migueljgranizo** [SoulDreamGames/SoulDreamGame#5]
La animación de andar va más lenta que la velocidad del personaje, eso hace que parezca que va patinando.

**Comment by martaquintana** [comment]
Sugerencia: al atacar pulsando E y volando el personaje podría hacer alguna animación cuando colisiona con el enemigo como por ejemplo abrir los brazos, para que parezca que le golpea, porque aunque el personaje va más rápido y desaparece el enemigo  no da la sensación de que le ha golpeado.

**Comment by SoulDreamGames** [comment]
En el primer caso, la transición entre animaciones estaba mal sincronizada, y al empezar a andar quedaba una sensación de patinar. En el segundo, en la nueva versión, aparecerán animaciones y sonidos para transmitir realimentación ante los ataques. 
¡Muchas gracias a ambos por el feedback!
