### ISSUE TITLE
Problemas al crear o unirse a una sala.

### ISSUE THREAD

**Issue by FelixdelasPozas** [SoulDreamGames/SoulDreamGame#6]
Al intentar crear una sala cuando ya existe una con ese nombre no se presenta un mensaje de error,
simplemente no hace nada ninguno de los botones. 
PASOS PARA REPRODUCIRLO
Empezar una partida y coger como
nombre de sala una que ya exista
----
A veces no funciona la unión a una partida existente, parpadea tanto el botón de unir como el de
crear sala, pero no avanza. 
PASOS PARA REPRODUCIRLO 
Intentar unirse a una partida existente.

**Comment by SoulDreamGames** [comment]
¡Hola! Gracias por el feedback.
Había un pequeño bug en la unión de partidas que ya ha sido resuelto. Aún con ello, la unión a salas solo puede realizarse durante el transcurso del Lobby, o hasta que se cubre el cupo máximo de 4 jugadores.
