### ISSUE TITLE
Fallo con los controles de vuelo

### ISSUE THREAD

**Issue by FelixdelasPozas** [SoulDreamGames/SoulDreamGame#7]
El vuelo es excesivamente difícil de controlar, además en cuanto golpeas el lateral de un edificio, se
cancela el vuelo y caes. 
PASOS PARA REPRODUCIRLO 
Activar el vuelo

**Comment by SoulDreamGames** [comment]
¡Hola! Hemos intentado mejorar el control general del vuelo para que sea más sencillo. Respecto a las colisiones, es una funcionalidad planificada, con el objetivo de intentar conseguir que los jugadores tengan en cuenta las consecuencias reales de volar a altas velocidades, incrementando así la dificultad de control ante mayor velocidad.
