### ISSUE TITLE
Resoluciones de pantalla duplicadas en el menú de settings

### ISSUE THREAD

**Issue by FelixdelasPozas** [SoulDreamGames/SoulDreamGame#8]
En el menú de settings, en la selección de tamaño de pantalla aparecen duplicadas las resoluciones.
PASOS PARA REPRODUCIRLO
Ir al menú de settings y seleccionar el tamaño de la pantalla de juego.

**Comment by martaquintana** [comment]
![image](https://user-images.githubusercontent.com/43533605/232117286-5977f0fd-0fca-4ada-94da-2219e98f592e.png)

**Comment by SoulDreamGames** [comment]
¡Gracias por el mensaje! Cada una de dichas resoluciones tiene asociado una tasa de Hz diferente internamente. Lo hemos actualizado para que muestre correctamente ese dato
