### ISSUE TITLE
Porcentajes que superan el cien por cien

### ISSUE THREAD

**Issue by martaquintana** [SoulDreamGames/SoulDreamGame#9]
![image](https://user-images.githubusercontent.com/43533605/232117440-ee95e7ef-b11e-4993-9502-da531d0dffdd.png)

También a veces al terminar una partida en la pantalla que muestra las estadísticas el botón “Confirm” se queda pillado y no hace nada hay que cerrar el juego.

**Comment by SoulDreamGames** [comment]
¡Gracias por el feedback! No se estaba actualizando correctamente el porcentaje de evacuados, y esto provocaba el error. ¡Ya está solucionado!
